### ISSUE TITLE
Error creating output files

### ISSUE THREAD

**Issue by elsatch** [candera/podcastifier#5]
Hi,

I'm trying to add two voices, intro and outro to create an episode. Programa fails with this output:

```
Exception in thread "main" java.lang.AssertionError: Assert failed: (= (channels s1) (channels s2))
    at dynne.sampled_sound$append.invoke(sampled_sound.clj:244)
    at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
    at clojure.core.protocols$fn__6041.invoke(protocols.clj:98)
    at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19)
    at clojure.core.protocols$seq_reduce.invoke(protocols.clj:27)
    at clojure.core.protocols$fn__6026.invoke(protocols.clj:53)
    at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
    at clojure.core$reduce.invoke(core.clj:6175)
    at podcastifier.main$resolve_reduce.invoke(main.clj:270)
    at podcastifier.main$append_all.invoke(main.clj:273)
    at podcastifier.main$resolve.invoke(main.clj:307)
    at podcastifier.main$resolve.invoke(main.clj:305)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.AFn.applyTo(AFn.java:151)
    at clojure.core$apply.invoke(core.clj:617)
    at clojure.core$memoize$fn__5049.doInvoke(core.clj:5735)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at podcastifier.main$_main.doInvoke(main.clj:323)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at podcastifier.main.main(Unknown Source)

```

I'm using this config file based on your examples:

```
{:version 7
 :output-file "lhmXX.wav"
  :sounds {
    :tr1 "EntrevistaconPaulTr1.WAV"
    :tr3 "EntrevistaconPaulTr3.WAV"
    :interview #{:tr1 :tr3}
    :music {:source "Shining_Thru_stinger.wav" :gain #db 2.0}
    :intro-music {:source :music :end #duration 6.0 :fade-out #duration 2.0}
    :outro-music {:source :music :tail #duration 6.0 :fade-in #duration 2.0}
    :podcast [:intro-music :interview :outro-music]}
    :final :podcast}

```

I've tried simplifying the file to include just in/track1/out but error remains the same.

I'm using MacOSX ElCapitan and Oracle JVM8. Any suggestion would be greatly appreciated!

**Comment by candera** [comment]
It looks like you're trying to combine stereo and mono sounds. Podcastifier doesn't know what to do in  that case. You need to either make the stereo bit mono or vice versa before combining. @russolsen might know more - this is really his baby these days.

**Comment by russolsen** [comment]
It looks to me like Craig is right, this is a mono -> stereo problem. Assuming you want a stereo output, perhaps you could try the following:

:tr1 {:source"EntrevistaconPaulTr1.WAV"  :->stereo true}

:tr3 {:source"EntrevistaconPaulTr3.WAV"  :->stereo true}
